# 协程、延迟函数调用、以及恐慌和恢复



### 协程（goroutine）

现代CPU一般含有多个核，并且一个核可能支持多线程。换句话说，现代CPU可以同时执行多条指令流水线。 为了将CPU的能力发挥到极致，我们常常需要使我们的程序支持并发（concurrent）计算。

并发计算是指若干计算可能在某些时间片段内同时运行的情形。 下面这两张图描绘了两种并发计算的场景。在此图中，A和B表示两个计算。 在第一种情形中，两个计算只在某些时间片段同时运行。 第二种情形称为并行（parallel）计算。在并行计算中，多个计算在任何时间点都在同时运行。并行计算属于特殊的并发计算。

![并发和并行](https://gfw.go101.org/article/res/concurrent-vs-parallel.png)



在Go编程中，协程是创建计算的唯一途径。

协程有时也被称为绿色线程。绿色线程是由程序的运行时（runtime）维护的线程。一个绿色线程的内存开销和情景转换（context switching）时耗比一个系统线程常常小得多。 只要内存充足，一个程序可以轻松支持上万个并发协程。

Go不支持创建系统线程，所以协程是一个Go程序内部唯一的并发实现方式。

每个Go程序启动的时候只有一个对用户可见的协程，我们称之为主协程。 一个协程可以开启更多其它新的协程。在Go中，开启一个新的协程是非常简单的。 我们只需在一个函数调用之前使用一个`go`关键字，即可让此函数调用运行在一个新的协程之中。 当此函数调用退出后，这个新的协程也随之结束了。我们可以称此函数调用为一个协程调用（或者为此协程的启动调用）。 一个协程调用的所有返回值（如果存在的话）必须被全部舍弃。

```go
package main

import (
	"log"
	"math/rand"
	"time"
)

func SayGreetings(greeting string, times int) {
	for i := 0; i < times; i++ {
		log.Println(greeting)
		d := time.Second * time.Duration(rand.Intn(5)) / 2
		time.Sleep(d) // 睡眠片刻（随机0到2.5秒）
	}
}

func main() {
	rand.Seed(time.Now().UnixNano())
	log.SetFlags(0)
	go SayGreetings("hi!", 10)
	go SayGreetings("hello!", 10)
	time.Sleep(2 * time.Second)
}
```

运行可能会得到如下的结果（也可能是其它结果）：

```
hi!
hello!
hello!
hello!
hello!
hi!
```

可以看出这里是不符合我们的预期的，程序并没有如我们所想各打印出十条hi！和hello！，原因很简单就是**主程序退出，协程也会跟着结束，不论是不是还有一些协程正在运行**；程序也没有如代码所写的那样先写出十条hi！再写出十条hello！，这是由于**两个协程并发进行，没有先后顺序**

*<!--和前面的几篇文章不同，上面的例子程序使用了`log`标准库而不是`fmt`标准库中的`Println`函数。 原因是`log`标准库中的打印函数是经过了同步处理的，而`fmt`标准库中的打印函数却没有被同步。 如果我们在上例中使用`fmt`标准库中的`Println`函数，则不同协程的打印可能会交织在一起。（虽然对此例来说，交织的概率很低。）-->*



### 并发同步（concurrency synchronization）

不同的并发计算可能共享一些资源，其中共享内存资源最为常见。 在一个并发程序中，常常会发生下面的情形：

- 在一个计算向一段内存**写数据**的时候，另一个计算从此内存段**读数据**，结果导致读出的数据的完整性得不到保证。
- 在一个计算向一段内存**写数据**的时候，另一个计算也向此段内存**写数据**，结果导致被写入的数据的完整性得不到保证。

这些情形被称为**数据竞争（data race）**。并发编程的一大任务就是要调度不同计算，控制它们对资源的访问时段，以使数据竞争的情况不会发生。 此任务常称为并发同步（或者数据同步）。<u>Go支持几种并发同步技术</u>。

<!--并发编程中的其它任务包括：-->

- <!--决定需要开启多少计算；-->
- <!--决定何时开启、阻塞、解除阻塞和结束哪些计算；-->
- <!--决定如何在不同的计算中分担工作负载。-->

Go支持几种[并发同步技术](https://gfw.go101.org/article/concurrent-synchronization-overview.html)。 其中， [通道](https://gfw.go101.org/article/channel.html)是最独特和最常用的。 但是，为了简单起见，这里我们将使用`sync`标准库包中的`WaitGroup`来同步上面这个程序中的主协程和两个新创建的协程。

`WaitGroup`类型有三个方法：`Add`、`Done`和`Wait`：

- `Add`方法用来注册新的需要完成的任务数。
- `Done`方法用来通知某个任务已经完成了。
- 一个`Wait`方法调用将阻塞（等待）到所有任务都已经完成之后才继续执行其后的语句。

示例：

```go
package main

import (
	"log"
	"math/rand"
	"time"
	"sync"
)

var wg sync.WaitGroup

func SayGreetings(greeting string, times int) {
	for i := 0; i < times; i++ {
		log.Println(greeting)
		d := time.Second * time.Duration(rand.Intn(5)) / 2
		time.Sleep(d)
	}
	wg.Done() // 通知当前任务已经完成。
}

func main() {
	rand.Seed(time.Now().UnixNano())
	log.SetFlags(0)
	wg.Add(2) // 注册两个新任务。
	go SayGreetings("hi!", 10)
	go SayGreetings("hello!", 10)
	wg.Wait() // 阻塞在这里，直到所有任务都已完成。
}
```

运行这个修改后的程序，我们将会发现所有的20条问候语都将在程序退出之前打印出来。



### 协程的状态

从上面这个的例子，我们可以看到一个活动中的协程可以处于两个状态：**运行状态**和**阻塞状态**。一个协程可以在这两个状态之间切换。 比如上例中的主协程在调用`wg.Wait`方法的时候，将从运行状态切换到阻塞状态；当两个新协程完成各自的任务后，主协程将从阻塞状态切换回运行状态。

下面的图片显示了一个协程的生命周期。

![协程状态](https://gfw.go101.org/article/res/goroutine-states.png)



注意，一个处于睡眠中的（通过调用`time.Sleep`）或者在等待系统调用返回的协程被认为是处于运行状态，而不是阻塞状态。

当一个新协程被创建的时候，它将自动进入运行状态，一个协程只能从运行状态而不能从阻塞状态退出。 如果因为某种原因而导致某个协程一直处于阻塞状态，则此协程将永远不会退出。 除了极个别的应用场景，在编程时我们应该尽量避免出现这样的情形。

一个处于阻塞状态的协程不会自发结束阻塞状态，它必须被另外一个协程通过某种并发同步方法来被动地结束阻塞状态。 如果一个运行中的程序当前**所有的协程**都处于阻塞状态，则这些协程将永远阻塞下去，程序将被视为死锁了。 **当一个程序死锁后，官方标准编译器的处理是让这个程序崩溃**。

比如下面这个程序将在运行两秒钟后崩溃。

```go
package main

import (
	"sync"
	"time"
)

var wg sync.WaitGroup

func main() {
	wg.Add(1)
	go func() {
		time.Sleep(time.Second * 2)
		wg.Wait() // 阻塞在此
	}()
	wg.Wait() // 阻塞在此
}
```

它的输出：

```
fatal error: all goroutines are asleep - deadlock!
```



### 协程的调度

并非所有处于运行状态的协程都在执行。在任一时刻，只能最多有和逻辑CPU数目一样多的协程在**同时执行**。 我们可以调用[`runtime.NumCPU`](https://golang.google.cn/pkg/runtime/#NumCPU)函数来查询当前程序可利用的逻辑CPU数目。 每个逻辑CPU在同一时刻只能最多执行一个协程。

协程之间是被频繁切换的，每个协程会被按需分配小的时间片，这样可以让每个协程都有机会被调用到

![协程详细状态](https://gfw.go101.org/article/res/goroutine-schedule.png)

标准编译器采纳了一种被称为[M-P-G模型](https://docs.google.com/document/d/1TTj4T2JO42uD5ID9e89oa0sLKhJYD0Y_kqxDv3I3XMw)的算法来实现协程调度。 其中，**M**表示系统线程，**P**表示逻辑处理器（并非上述的逻辑CPU），**G**表示协程。 大多数的调度工作是通过逻辑处理器（**P**）来完成的。 **P**把**G**交给**M**来执行

在运行时刻，我们可以调用[`runtime.GOMAXPROCS`](https://golang.google.cn/pkg/runtime/#GOMAXPROCS)函数来获取和设置逻辑处理器的数量，也可以通过设置`GOMAXPROCS`环境变量来设置一个Go程序的初始逻辑处理器数量。 <!--对于官方标准编译器，在Go 1.5之前，默认初始逻辑处理器的数量为1；自从Go 1.5之后，默认初始逻辑处理器的数量和逻辑CPU的数量一致。 此新的默认设置在大多数情况下是最佳选择。但是对于某些文件操作十分频繁的程序，设置一个大于`runtime.NumCPU()`的`GOMAXPROCS`值可能是有好处的。-->



### 延迟函数调用（deferred function call）

在Go中，一个函数调用可以跟在一个`defer`关键字后面，形成一个延迟函数调用。 和协程调用类似，被延迟的函数调用的所有返回值必须全部被舍弃。

<!--事实上，每个协程维护着两个调用堆栈。-->

- <!--一个是正常的函数调用堆栈。在此堆栈中，相邻的两个调用存在着调用关系。晚进入堆栈的调用被早进入堆栈的调用所调用。 此堆栈中最早被推入的调用是对应协程的启动调用。-->
- <!--另一个堆栈是上面提到的延迟调用堆栈。处于延迟调用堆栈中的任意两个调用之间不存在调用关系。-->

当一个函数调用被延迟后，它不会立即被执行。它将被推入由当前协程维护的一个延迟调用堆栈。执行顺序与入栈出栈顺序一致，参考下例。

```go
package main

import "fmt"

func main() {
	defer fmt.Println("The third line.")
	defer fmt.Println("The second line.")
	fmt.Println("The first line.")
}
```

输出结果：

```
The first line.
The second line.
The third line.
```
一个更为复杂的例子：（0 1 2 3 4 5 6 7 8 9）

```go
package main

import "fmt"

func main() {
	defer fmt.Println("9")
	fmt.Println("0")
	defer fmt.Println("8")
	fmt.Println("1")
	if false {
		defer fmt.Println("not reachable")
	}
	defer func() {
		defer fmt.Println("7")
		fmt.Println("3")
		defer func() {
			fmt.Println("5")
			fmt.Println("6")
		}()
		fmt.Println("4")
	}()
	fmt.Println("2")
	return
	defer fmt.Println("not reachable")
}
```



### 一个延迟调用可以修改包含此延迟调用的最内层函数的返回值

一个例子：

```go
package main

import "fmt"

func Triple(n int) (r int) {
	defer func() {
		r += n // 修改返回值
	}()

	return n + n // <=> r = n + n; return
}

func main() {
	fmt.Println(Triple(5)) // 15
}
```



### 协程和延迟调用的实参的估值时刻

一个协程调用或者延迟调用的实参是在<u>此调用发生时被估值</u>的。更具体地说，

- 对于一个延迟函数调用，它的实参是在此调用被推入延迟调用堆栈的时候被估值的。
- 对于一个协程调用，它的实参是在此协程被创建的时候估值的。

一个匿名函数体内的表达式是在此函数被执行的时候才会被逐个估值的，不管此函数是被普通调用还是延迟/协程调用。

一个例子：

```go
package main

import "fmt"

func main() {
	func() {
		for i := 0; i < 3; i++ {
			defer fmt.Println("a:", i)
		}
	}()
	fmt.Println()
	func() {
		for i := 0; i < 3; i++ {
			defer func() {
				fmt.Println("b:", i)
			}()
		}
	}()
}
```

运行之，将得到如下结果：

```
a: 2
a: 1
a: 0

b: 3
b: 3
b: 3
```

我们可以对第二个循环略加修改（使用两种方法），使得它和第一个循环打印出相同的结果。

```go
		for i := 0; i < 3; i++ {
			defer func(i int) {
				// 此i为形参i，非实参循环变量i。
				fmt.Println("b:", i)
			}(i)
		}
```

或者

```go
		for i := 0; i < 3; i++ {
			i := i // 在下面的调用中，左i遮挡了右i。
			       // <=> var i = i
			defer func() {
				// 此i为上面的左i，非循环变量i。
				fmt.Println("b:", i)
			}()
		}
```



同样的估值时刻规则也适用于协程调用。下面这个例子程序将打印出`123 789`。

```go
package main

import "fmt"
import "time"

func main() {
	var a = 123
	go func(x int) {
		time.Sleep(time.Second)
		fmt.Println(x, a) // 123 789
	}(a)

	a = 789

	time.Sleep(2 * time.Second)
}
```

顺便说一句，使用`time.Sleep`调用来做并发同步不是一个好的方法。 如果上面这个程序运行在一个满负荷运行的电脑上，此程序可能在新启动的协程可能还未得到执行机会的时候就已经退出了。 在正式的项目中，我们应该使用[并发同步技术](https://gfw.go101.org/article/concurrent-synchronization-overview.html)一文中列出的方法来实现并发同步。



### 恐慌（panic）和恢复（recover）

Go不支持异常抛出和捕获，而是推荐使用返回值显式返回错误。 不过，Go支持一套和异常抛出/捕获类似的机制。此机制称为恐慌/恢复（panic/recover）机制。

我们可以调用内置函数`panic`来产生一个恐慌以使当前协程进入恐慌状况。

进入恐慌状况是另一种使当前函数调用开始返回的途径。 一旦一个函数调用产生一个恐慌，此函数调用将立即进入它的退出阶段，在此函数调用中被推入堆栈的延迟调用将按照它们被推入的顺序逆序执行。

通过在一个延迟函数调用之中调用内置函数`recover`，当前协程中的一个恐慌可以被消除，从而使得当前协程重新进入正常状况。

在一个处于恐慌状况的协程退出之前，其中的恐慌不会蔓延到其它协程。 如果一个协程在恐慌状况下退出，它将使整个程序崩溃。

内置函数`panic`和`recover`的声明原型如下：

```go
func panic(v interface{})
func recover() interface{}
```

<!--我们可以暂时将空接口类型`interface{}`视为很多其它语言中的`any`或者`Object`类型。 换句话说，在一个`panic`函数调用中，我们可以传任何实参值。-->

一个`recover`函数的返回值为其所恢复的恐慌在产生时被一个`panic`函数调用所消费的参数。

下面这个例子展示了如何产生一个恐慌和如何消除一个恐慌。

```go
package main

import "fmt"

func main() {
	defer func() {
		fmt.Println("正常退出")
	}()
	fmt.Println("嗨！")
	defer func() {
		v := recover()
		fmt.Println("恐慌被恢复了：", v)
	}()
	panic("拜拜！") // 产生一个恐慌
	fmt.Println("执行不到这里")
}
```

它的输出结果：

```
嗨！
恐慌被恢复了： 拜拜！
正常退出
```



下面的例子在一个新协程里面产生了一个恐慌，并且此协程在恐慌状况下退出，所以整个程序崩溃了。

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("hi!")

	go func() {
		time.Sleep(time.Second)
		panic(123)
	}()

	for {
		time.Sleep(time.Second)
	}
}
```

运行之，输出如下：

```
hi!
panic: 123

goroutine 5 [running]:
...
```



Go运行时（runtime）会在若干情形下产生恐慌，比如一个整数被0除的时候。下面这个程序将崩溃退出。

```go
package main

func main() {
	a, b := 1, 0
	_ = a/b
}
```

它的输出：

```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
...
```



一般说来，恐慌用来表示正常情况下不应该发生的逻辑错误。 如果这样的一个错误在运行时刻发生了，则它肯定是由于某个bug引起的。 另一方面，非逻辑错误是现实中难以避免的错误，它们不应该导致恐慌。 我们必须正确地对待和处理非逻辑错误。

### 一些致命性错误不属于恐慌

对于官方标准编译器来说，很多致命性错误（比如堆栈溢出和内存不足）不能被恢复。它们一旦产生，程序将崩溃。



# 一些恐慌/恢复用例



### 用例1：避免恐慌导致程序崩溃

这可能是最常见的panic/recover用例了。 此用例广泛地使用于并发程序中，尤其是响应大量用户请求的应用。

一个例子：

```go
package main

import "errors"
import "log"
import "net"

func main() {
	listener, err := net.Listen("tcp", ":12345")
	if err != nil {
		log.Fatalln(err)
	}
	for {
		conn, err := listener.Accept()
		if err != nil {
			log.Println(err)
		}
		// 在一个新协程中处理客户端连接。
		go ClientHandler(conn)
	}
}

func ClientHandler(c net.Conn) {
	defer func() {
		if v := recover(); v != nil {
			log.Println("捕获了一个恐慌：", v)
			log.Println("防止了程序崩溃")
		}
		c.Close()
	}()
	panic("未知错误") // 演示目的产生的一个恐慌
}
```

运行此服务器程序，并在另一个终端窗口运行`telnet localhost 12345`，我们可以观察到服务器程序不会因为客户连接处理协程中的产生的恐慌而导致崩溃。

如果我们在上例中不捕获客户连接处理协程中的潜在恐慌，则这样的恐慌将使整个程序崩溃。



### 用例2：自动重启因为恐慌而退出的协程

当在一个协程将要退出时，程序侦测到此协程是因为一个恐慌而导致此次退出时，我们可以立即重新创建一个相同功能的协程。 一个例子：

```go
package main

import "log"
import "time"

func shouldNotExit() {
	for {
		time.Sleep(time.Second) // 模拟一个工作负载
		// 模拟一个未预料到的恐慌。
		if time.Now().UnixNano() & 0x3 == 0 {
			panic("unexpected situation")
		}
	}
}

func NeverExit(name string, f func()) {
	defer func() {
		if v := recover(); v != nil { // 侦测到一个恐慌
			log.Printf("协程%s崩溃了，准备重启一个", name)
			go NeverExit(name, f) // 重启一个同功能协程
		}
	}()
	f()
}

func main() {
	log.SetFlags(0)
	go NeverExit("job#A", shouldNotExit)
	go NeverExit("job#B", shouldNotExit)
	select{} // 永久阻塞主线程
}
```



### 用例3：使用`panic`/`recover`函数调用模拟长程跳转

有时，我们可以使用`panic`/`recover`函数调用来模拟跨函数跳转，尽管一般这种方式并不推荐使用。 这种跳转方式的可读性不高，代码效率也不是很高，唯一的好处是它有时可以使代码看上去不是很啰嗦。

在下面这个例子中，一旦一个恐慌在一个内嵌函数中产生，当前协程中的执行将会跳转到延迟调用处。

```go
package main

import "fmt"

func main() {
	n := func () (result int)  {
		defer func() {
			if v := recover(); v != nil {
				if n, ok := v.(int); ok {
					result = n
				}
			}
		}()

		func () {
			func () {
				func () {
					// ...
					panic(123) // 用恐慌来表示成功返回
				}()
				// ...
			}()
		}()
		// ...
		return 0
	}()
	fmt.Println(n) // 123
}
```



### 用例4：使用`panic`/`recover`函数调用来减少错误检查代码

一个例子：

```go
func doSomething() (err error) {
	defer func() {
		err = recover()
	}()

	doStep1()
	doStep2()
	doStep3()
	doStep4()
	doStep5()

	return
}

// 在现实中，各个doStepN函数的原型可能不同。
// 每个doStepN函数的行为如下：
// * 如果已经成功，则调用panic(nil)来制造一个恐慌
//   以示不需继续；
// * 如果本步失败，则调用panic(err)来制造一个恐慌
//   以示不需继续；
// * 不制造任何恐慌表示继续下一步。
func doStepN() {
	...
	if err != nil {
		panic(err)
	}
	...
	if done {
		panic(nil)
	}
}
```

下面这段同功能的代码比上面这段代码看上去要啰嗦一些。

```go
func doSomething() (err error) {
	shouldContinue, err := doStep1()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep2()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep3()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep4()
	if !shouldContinue {
		return err
	}
	shouldContinue, err = doStep5()
	if !shouldContinue {
		return err
	}

	return
}

// 如果返回值err不为nil，则shouldContinue一定为true。
// 如果shouldContinue为true，返回值err可能为nil或者非nil。
func doStepN() (shouldContinue bool, err error) {
	...
	if err != nil {
		return false, err
	}
	...
	if done {
		return false, nil
	}
	return true, nil
}
```

但是，这种`panic`/`recover`函数调用的使用方式一般并不推荐使用，因为它的效率略低一些，并且这种用法不太符合Go编程习俗。